add pre-commit tool
kpi-web-guild/django-girls-blog-igorkruglyak pull request #15
Opened 2019-06-17 09:07 UTC by igorkruglyak

2019-06-17 10:29 UTC, webknjaz requested changes
1) Link the issue using `Closes` keyword.
2) Fix the commit message and PR title style to match the recommendations you've learned from the articles.

2019-06-17 11:06 UTC, igorkruglyak commented
Closes

2019-06-17 11:07 UTC, webknjaz commented
Read  GitHub docs about keywords

2019-06-17 11:11 UTC, igorkruglyak commented
Closes #15

2019-06-17 11:12 UTC, webknjaz commented
Put that into PR description and a commit message.

2019-06-17 11:17 UTC, igorkruglyak commented
closes #15 
Fix PR

2019-06-17 11:18 UTC, webknjaz commented
That's a comment to the PR. I ask you to change the PR description.

2019-06-18 20:03 UTC, igorkruglyak commented
I do not understand what needs to be done. please help

2019-06-18 20:06 UTC, webknjaz commented
It's on top of this page.

2019-06-18 20:10 UTC, igorkruglyak commented
change Add pre-commit configuration #15 ?

2019-06-18 20:22 UTC, igorkruglyak commented
that's right?

2019-06-18 20:33 UTC, webknjaz commented
Don't duplicate the PR title. The description should augment it if needed. Add more details.

2019-06-18 20:33 UTC, webknjaz commented
After fixing the PR, rewrite the message in this commit accordingly: https://github.com/kpi-web-guild/django-girls-blog-igorkruglyak/pull/15/commits/83b28abcd56d1a66bce106ad6f27d6c14cc77c09

2019-06-18 20:45 UTC, webknjaz commented
Hey @schenkh, would you mind helping out Ihor here?

2019-06-18 20:46 UTC, webknjaz commented
@igorkruglyak format your PR title in a nice readable way, using `*` for list items.

2019-06-18 21:00 UTC, igorkruglyak commented
what should i do next? how to do it: 'rewrite the message in this commit accordingly'

2019-06-18 21:02 UTC, webknjaz commented
#4 and #5 should help you. Also, use Google and StackOverflow. Search for interactive rebase and rewriting branches/commits, also force push.

2019-06-18 21:16 UTC, igorkruglyak commented
насправді я ще працюю над покращенням своєї англійської, поки що. ну, відповідно, не завжди все вірно розумію. голова вже кипить на елементарних речах. мені що, локально в гіті переписати в коміті повідомлення? запушити коміт по новому? що робити з цим пулл реквестом? Напиши українською, будь ласка, покроково, що саме треба виправити, а як його зробити не буде проблемою для мене.

2019-06-18 21:18 UTC, webknjaz commented
саме так і треба зробити. як перепишеш і запушиш гілку, то це відобразиться у ПР автоматично.

2019-06-19 00:04 UTC, webknjaz commented
Що гілку ти створював читачам комітів твоїх нецікаво. А ще, ти не встановлюєш пре-коміт цим комітом. Треба писати який ефект буде від застосування.

2019-06-19 07:00 UTC, schenkh commented
@webknjaz Здається Ігор вже розібрався. Або я ще якось можу допомогти?

2019-06-19 08:29 UTC, webknjaz commented
@schenkh із вмістом коміта: поясниш як покращити?

2019-06-19 12:18 UTC, schenkh commented
Переглянув .pre-commit-config.yaml і він, на мою думку, виглядає як потрібно. А за змістом коміта я припускаю що потрібно змінити "Install pre-commit" на "Add pre-commit configuration" чи "Configure pre-commit rules" щоб був більш зрозумілий сенс зроблених змін.

2019-06-19 12:19 UTC, webknjaz commented
а ще розширений опис коміта має непотрібні дані і погано форматований

2019-06-19 12:47 UTC, schenkh commented
Так, тепер бачу, коли клонував гілку. @igorkruglyak коли ми обговорювали опис коміту з @webknjaz я для себе зробив такий висновок що назва повинна бути "Що ви зробили в імперативному настрої" а тіло: "Поясніть, що і чому ви зробили - а не як..."

2019-06-19 14:57 UTC, webknjaz commented
іноді треба і "як", але високорівнево і лише тоді, коли з коміта не очевидно, наприклад, якщо щось неймовірно складне і заплутане.

2019-06-19 20:58 UTC, igorkruglyak commented
Дуже дякую вам обом за підказки.
Так піде?

Add pre-commit configuration

Install pre-commit for automatically identifying issues
Added .pre-commit-config.yaml config 
Added the following hooks:
 *   no-commit-to-branch
 *   add-trailing-comma
 *   remove-tabs
 *   trailing-whitespace
 *   check-merge-conflict
 *   double-quote-string-fixer
 *   requirements-txt-fixer
 *   check-yaml
 *   check-docstring-first
 *   end-of-file-fixer
 *   name-tests-test
 *   check-ast
 *   debug-statements
 *   flake8
 *   pydocstyle
 *   pylint using "local" mode
 *   mypy

2019-06-19 20:58 UTC, webknjaz commented
ні, ти нічого не інсталюєш. це неправда.

2019-06-19 21:00 UTC, igorkruglyak commented
Added?

2019-06-19 21:01 UTC, webknjaz commented
ти конфіг додаєш, не програму

2019-06-19 21:03 UTC, igorkruglyak commented
Може так 
Added .pre-commit-config.yaml for automatically identifying issues

2019-06-19 21:10 UTC, webknjaz commented
Я вже писав вище взагалі: не треба повторювати заголовок коміта в доповненому описі.

2019-06-19 21:13 UTC, webknjaz commented
Щось типу

```console
Configure the pre-commit tool

Closes #15

Ref: https://pre-commit.com

This commit includes the initial configuration for
the following pre-commit hooks:
* no-commit-to-branch
* add-trailing-comma
* remove-tabs
* trailing-whitespace
* check-merge-conflict
* double-quote-string-fixer
* requirements-txt-fixer
* check-yaml
* check-docstring-first
* end-of-file-fixer
* name-tests-test
* check-ast
* debug-statements
* flake8
* pydocstyle
* pylint using "local" mode
* mypy
```

2019-06-19 21:18 UTC, igorkruglyak commented
Дякую! Так справді набагато інформативніше.

2019-06-19 21:20 UTC, webknjaz commented
Це потім буде в дереві гіта і треба думати про те, щоб повідомлення було цінним для того, хто це читатиме в майбутньому. Це можеш бути ти або хтось інший.
Якщо правильно вести історію в гіті, то легко штукати коли проблеми виникли при необхідності. Також зрозуміло стає хід думок і послідовність змін. Стилістика теж важлива, варто слідувати практикам, якими послуговуються розробники самого гіта.

2019-06-19 21:21 UTC, webknjaz commented
Не забувай, що змінити й коміт треба, бо він теж потрапить до історії.

2019-06-19 21:23 UTC, igorkruglyak commented
Зрозумів. Дякую. Зараз зміню.

2019-06-23 18:03 UTC, webknjaz commented
> Closes #15

оце неправильно. має бути номер іш'ю, яке автоматично закриється, якщо змерджити цей ПР.

2019-06-23 18:05 UTC, webknjaz commented on .pre-commit-config.yaml
> +    - id: pylint
The task was to use a "local" mode for this linter. Here's an example: https://github.com/sanitizers/octomachinery/blob/93899d4/.pre-commit-config.yaml#L51-L58

2019-06-26 14:08 UTC, webknjaz requested changes
Are all checks green/passed when you run `python3.7 -m pre_commit` locally?

2019-06-26 14:08 UTC, webknjaz commented on .pre-commit-config.yaml
> +args: []
This is broken.

2019-06-26 17:27 UTC, igorkruglyak commented on .pre-commit-config.yaml
> +args: []
thanks

2019-06-26 17:28 UTC, webknjaz commented on .pre-commit-config.yaml
> +- repo: local
Use the same indentation style for all parts of this YAML file.

2019-06-26 17:29 UTC, webknjaz commented
So what's the output of `python3.7 -m pre_commit`?

2019-06-26 17:44 UTC, igorkruglyak commented on .pre-commit-config.yaml
> +- repo: local
> So what's the output of `python3.7 -m pre_commit`?

Check Yaml...........................................(no files to check)Skipped
Debug Statements (Python)............................(no files to check)Skipped
Tests should end in _test.py.........................(no files to check)Skipped
Fix requirements.txt.................................(no files to check)Skipped
Trim Trailing Whitespace.............................(no files to check)Skipped
Fix End of Files.....................................(no files to check)Skipped
Check docstring is first.............................(no files to check)Skipped
Fix double quoted strings............................(no files to check)Skipped
Check python ast.....................................(no files to check)Skipped
Don't commit to branch...................................................Passed
Check for merge conflicts............................(no files to check)Skipped
flake8...............................................(no files to check)Skipped
Add trailing commas..................................(no files to check)Skipped
CRLF end-lines checker...............................(no files to check)Skipped
CRLF end-lines remover...............................(no files to check)Skipped
No-tabs checker......................................(no files to check)Skipped
Tabs remover.........................................(no files to check)Skipped
Verifying PEP257 Compliance..........................(no files to check)Skipped
mypy.................................................(no files to check)Skipped
PyLint...............................................(no files to check)Skipped

2019-06-26 18:13 UTC, webknjaz commented on .pre-commit-config.yaml
> +- repo: local
Reply to things where asked. It's a comment to the line 44.

2019-06-26 18:14 UTC, webknjaz commented on .pre-commit-config.yaml
> +- repo: local
And this comment asks about another thing you ignored. See above.

2019-06-26 20:25 UTC, igorkruglyak commented on .pre-commit-config.yaml
> +- repo: local
Мені не зовсім зрозуміло. Помістити цю відповідь нижче під тим питанням що виведе команда python3.7 -m pre_commit? Чи ще щось виправити?

2019-06-26 20:49 UTC, webknjaz commented on .pre-commit-config.yaml
> +- repo: local
Перше повідомлення у треді до цього рядка про відступи, а твоя відповідь ні до чого тут

2019-06-26 20:51 UTC, webknjaz approved these changes

2019-06-26 21:04 UTC, igorkruglyak commented on .pre-commit-config.yaml
> +- repo: local
Ну так, переплутав, не туди вліпив, вибач. Видалити? Щось маю зробити, щоб правильно було?

2019-06-27 06:05 UTC, webknjaz commented on .pre-commit-config.yaml
> +- repo: local
Просто на майбутнє не плутай. Ну і ти от змінив відступи, а тут не позначив що вирішено. Кнопка для цього внизу є + можна написати, бо от мені сповіщення не приходять про пуші. Відповідно можеш довго чекати поки я сам згадаю перевірити.

2019-06-27 06:06 UTC, webknjaz commented
Можеш мерджити це

2019-06-28 18:32 UTC, igorkruglyak commented
> Можеш мерджити це

Маєш на увазі локально в себе?

2019-06-28 21:57 UTC, webknjaz commented
можна кнопкою у цьому пул реквесті

2019-06-28 22:02 UTC, igorkruglyak commented
> Можеш мерджити це

Маєш на увазі локально в себе?

> можна кнопкою у цьому пул реквесті

Merging is blocked  - ось це тут пише в мене

2019-06-29 08:05 UTC, webknjaz commented
Можеш скриншот прислати?

2019-06-29 08:07 UTC, webknjaz commented
Налаштування трохи змінив, має бути зелена кнопка тепер.

2019-06-29 08:11 UTC, igorkruglyak commented
> Налаштування трохи змінив, має бути зелена кнопка тепер.

Так, тепер зелена.

2019-06-29 08:11 UTC, merged

2019-06-29 18:12 UTC, webknjaz commented
Тепер берися за інтеграцію трейвіса