Add separation dependency of files
kpi-web-guild/django-girls-blog-igorkruglyak pull request #24
Opened 2019-07-31 21:40 UTC by igorkruglyak

2019-07-31 22:56 UTC, webknjaz commented on test-requirements.txt
> +pylint-django==2.0.11
This line is unrelated to this PR

2019-07-31 22:57 UTC, webknjaz commented
> Add separation dependency of files

"Put test deps into requirements file"

2019-08-01 21:24 UTC, igorkruglyak commented on test-requirements.txt
> +pylint-django==2.0.11
Ok, how do I fix it?

2019-08-02 14:08 UTC, webknjaz commented on test-requirements.txt
> +pylint-django==2.0.11
Easy: don't add this line.

2019-08-02 22:53 UTC, igorkruglyak commented on test-requirements.txt
> +pylint-django==2.0.11
What is wrong now?

2019-08-05 21:15 UTC, webknjaz commented
@igorkruglyak why did you delete all of the dependencies? You're supposed to just move them into a file.

2019-08-05 21:17 UTC, webknjaz commented on test-requirements.txt
> +pylint-django==2.0.11
You erased two lines more than needed.

2019-08-06 20:37 UTC, webknjaz requested changes

2019-08-06 20:37 UTC, webknjaz commented on test-requirements.txt
> +pylint-django==2.0.11
This line is still not needed.

2019-08-06 21:16 UTC, webknjaz approved these changes

2019-08-07 22:18 UTC, merged