Dynamic data in templates
kpi-web-guild/django-girls-blog-igorkruglyak pull request #36
Opened 2020-06-05 12:16 UTC by igorkruglyak

Modified views to display posts from database

2020-06-05 16:36 UTC, webknjaz commented on mysite/settings.py
> +        'NAME': (
Looks like you forgot to rebase on top of `origin/master` (did you update your local repo from github remote with `git fetch --all` or `git pull --rebase`?).

2020-06-05 16:39 UTC, webknjaz commented
You need to fix the linter offenses and typos in var names. First of all, check that the code works by running your app because now it doesn't since you refer to a non-existing variable name.

2020-06-06 22:22 UTC, webknjaz commented on .pre-commit-config.yaml
> +    - --load-plugins=pylint_django
This should be submitted separately. It does not do "Dynamic data in templates"

2020-06-07 21:59 UTC, webknjaz commented
@igorkruglyak

> Dynamic data in templates

What does this mean, again?

2020-06-14 20:28 UTC, webknjaz submitted a review, later dismissed

2020-06-14 20:41 UTC, webknjaz commented on blog/views.py
> +    posts = (
```suggestion
    posts___ = (
```

2020-06-14 20:44 UTC, webknjaz approved these changes

2020-06-14 20:45 UTC, webknjaz requested changes
Well done!

2020-06-14 20:45 UTC, webknjaz commented on blog/views.py
> +from django.utils import timezone
comment1

2020-06-14 20:45 UTC, webknjaz commented on blog/views.py
> +    )
comment2

2020-06-14 20:46 UTC, webknjaz approved these changes

2020-06-14 20:47 UTC, slsh1o approved these changes
Good job.

2020-06-14 20:47 UTC, merged

2020-06-14 20:48 UTC, gaupt commented on blog/views.py
> +    )
!!!